stages:    
    - build 

test:
    stage: build
    image: "lluki/sockeye-build"
    script:
        - "make build/test_report.txt"
    artifacts:
        paths:
            - "build/test_report.txt"
